server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

workload-api:
  url: ${WORKLOAD_API_URL:http://localhost:8080}

service:
  name: photo-service

print-service:
  url: ${PRINT_SERVICE_URL:http://localhost:8083}
  mtls-url: ${PRINT_SERVICE_MTLS_URL:https://print-service:8443}

logging:
  level:
    com.example.photoservice: INFO
    com.example.spiffe: INFO
    root: INFO

