server:
  port: 8083
  mtls:
    port: ${MTLS_PORT:8443}

spring:
  datasource:
    url: jdbc:postgresql://postgres-print:5432/print_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false

user-service:
  url: ${USER_SERVICE_URL:http://user-service:8081}

photo-service:
  url: ${PHOTO_SERVICE_URL:http://photo-service:8082}

workload-api:
  url: ${WORKLOAD_API_URL:http://workload-api-service:8080}

service:
  name: print-service

logging:
  level:
    com.example.printservice: INFO
    root: INFO

